---
name: luv-coffee-fe ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-ci:
    name: Run CI
    runs-on: ubuntu-latest

    # permissions:
    #   actions: read # for github/codeql-action
    #   contents: read # for github/codeql-action
    #   security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ngnestpostgres'

      - name: Install Packages
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_FE_SHARED_TOKEN }}

      - name: Build
        run: npm run build:prod

      - name: Lint
        run: npm run lint

      - name: Unit Test
        run: npm run test:ci

      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          exit-code: 0
          format: table

      - name: Run Trivy for HIGH,CRITICAL CVEs (blocking)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          format: 'sarif'
          output: 'trivy-results.sarif'

      # Requires Advanced Security which is avalabale only for public and GitHub Enterprise
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        # if: always()
        with:
          sarif_file: trivy-results.sarif
          category: my-analysis-tool